In [1]:
import numpy as np

In [3]:
# sigmoid function
def nonlin(x, deriv = False):
    if(deriv == True):
        return x * (1 - x)
    
    return 1 / (1 + np.exp(-x))

In [7]:
# Input dataset
x = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])

# Output dataset
y = np.array([[0, 0, 1, 1]]).T

In [8]:
x

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [9]:
y

array([[0],
       [0],
       [1],
       [1]])

In [10]:
np.random.seed(1)

In [11]:
# Initialize weights randomly with mean 0
syn0 = 2 * np.random.random((3, 1)) - 1

In [14]:
for itr in xrange(1000):
    # forward propagation
    l0 = x
    l1 = nonlin(np.dot(x, syn0))
    
    print l1
    
    # how much did we miss?
    l1_error = y - l1
    
    l1_delta = l1_error * nonlin(l1,True)
        
    syn0 += np.dot(l0.T,l1_delta)

[[ 0.32550793]
 [ 0.45332188]
 [ 0.41995875]
 [ 0.55437725]]
error
[[-0.32550793]
 [-0.45332188]
 [ 0.58004125]
 [ 0.44562275]]
Delta
[[-0.07146608]
 [-0.11234275]
 [ 0.14129422]
 [ 0.11008803]]
syn0
[[ 0.65701265]
 [ 0.53906065]
 [-0.66099969]]
