In [1]:
import numpy as np

In [4]:
X = np.array([[3, 5], [5, 1], [10, 2]], dtype=float)
y = np.array([[75], [82], [93]], dtype=float)

In [3]:
X

array([[  3.,   5.],
       [  5.,   1.],
       [ 10.,   2.]])

In [5]:
y

array([[ 75.],
       [ 82.],
       [ 93.]])

# Scale data

In [6]:
X = X/np.max(X, axis=0)
y = y/100 # Max test score is 100

In [7]:
X

array([[ 0.3,  1. ],
       [ 0.5,  0.2],
       [ 1. ,  0.4]])

In [8]:
y

array([[ 0.75],
       [ 0.82],
       [ 0.93]])

# Neural Network Class

In [22]:
class Neural_Network(object):
    def __init__(self):
        # Define HyperParameter
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        
        # Weights (Parameter)
        self.W1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)
        
    def forward(self, X):
        # Propagate input through network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3)
        
        return yHat
    
    def sigmoid(self, z):
        # Apply sigmoid activation function
        return 1/(1 + np.exp(-z))

In [23]:
NN = Neural_Network()

In [25]:
yHat = NN.forward(X)

In [26]:
yHat

array([[ 0.6090269 ],
       [ 0.62780926],
       [ 0.66001978]])

In [27]:
y

array([[ 0.75],
       [ 0.82],
       [ 0.93]])